version: "3.9"
services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redismod
    env_file: .env
    ports:
      - $REDIS_PORT:$REDIS_PORT
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    depends_on:
      - redis
    env_file: .env
    environment:
      - SERVER_HOST=$SERVER_HOST
      - SERVER_PORT=$SERVER_PORT
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_USER=$REDIS_USER
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_DB_INDEX=$REDIS_DB_INDEX
    ports:
      - $SERVER_PORT:$SERVER_PORT
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure